language: python
python:
 - "3.6.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov

script:
  - nosetests --with-coverage --cover-package=test

after_success:
  - coveralls

cache: pip
